// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TMap.Persistence;

#nullable disable

namespace TMap.Persistence.Migrations
{
    [DbContext(typeof(TMapDbContext))]
    [Migration("20230709113907_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.8");

            modelBuilder.Entity("TMap.Domain.Entities.Material.Material", b =>
                {
                    b.Property<int>("MaterialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("material_id");

                    b.Property<string>("ColorHexCode")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("TEXT")
                        .HasColumnName("color");

                    b.Property<double>("Density")
                        .HasColumnType("REAL")
                        .HasColumnName("density");

                    b.Property<double>("Humidity")
                        .HasColumnType("REAL")
                        .HasColumnName("humidity");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<double>("ThermalConductivity")
                        .HasColumnType("REAL");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasColumnName("type");

                    b.HasKey("MaterialId");

                    b.ToTable("materials", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
